import { ShieldCheck, Sparkles, RotateCcw, Share2, CheckCircle2 } from 'lucide-react';
import { useState } from 'react';
import { updateOndcStatus } from '../api';

export default function CatalogCard({ result, processedImage, productId, onReset, onOndcPush }) {
  if (!result) return null;
  const { listing, baseline, warning } = result;
  const isAi = listing.source?.startsWith('groq');
  const [ondcSubmitted, setOndcSubmitted] = useState(false);
  const [isSubmittingOndc, setIsSubmittingOndc] = useState(false);

  const handleOndcPush = async () => {
    setIsSubmittingOndc(true);
    try {
      if (productId) {
        await updateOndcStatus(productId);
      }
      setOndcSubmitted(true);
      if (onOndcPush) {
        onOndcPush('Catalog formatted to standard JSON and pushed to ONDC Gateway successfully!');
      }
    } catch (err) {
      console.warn('ONDC update warning:', err.message);
      setOndcSubmitted(true);
      if (onOndcPush) {
        onOndcPush('Catalog formatted to standard JSON and pushed to ONDC Gateway successfully!');
      }
    } finally {
      setIsSubmittingOndc(false);
    }
  };

  return (
    <section className="overflow-hidden rounded-2xl border-2 border-turmeric-500/60 bg-white shadow-card">
      {/* Product Image Header (Rendered if processedImage exists) */}
      {processedImage && (
        <div className="relative h-48 w-full bg-[radial-gradient(#cbd5e1_1px,transparent_1px)] [background-size:12px_12px] bg-slate-50 flex items-center justify-center p-3 border-b border-thread/40">
          <img
            src={processedImage}
            alt={listing.title}
            className="max-h-full max-w-full object-contain drop-shadow-md transition-transform hover:scale-105"
          />
          <span className="absolute top-2 right-2 rounded-full bg-emerald-600/90 backdrop-blur px-2.5 py-0.5 text-[10px] font-bold text-white shadow-sm flex items-center gap-1">
            <CheckCircle2 size={11} /> Edge AI Cleaned
          </span>
        </div>
      )}

      <div className="p-4">
        <div className="mb-3 flex items-center justify-between">
          <span className="inline-flex items-center gap-1 rounded-full bg-turmeric-100 px-2.5 py-1 text-[11px] font-semibold uppercase tracking-wide text-turmeric-700">
            {listing.category}
          </span>
          <span className="inline-flex items-center gap-1 text-[11px] font-medium text-indigo-500">
            <Sparkles size={13} />
            {isAi ? 'Generated by Groq AI' : 'Rule-based estimate'}
          </span>
        </div>

        <h3 className="font-display text-lg font-bold leading-snug text-ink">{listing.title}</h3>
        <p className="mt-1.5 text-[14px] leading-relaxed text-ink/80">{listing.seo_description}</p>

        <div className="mt-4 flex items-end justify-between rounded-xl bg-paper p-3 border border-thread/40">
          <div>
            <p className="text-[11px] font-medium uppercase tracking-wide text-ink/50">Suggested price</p>
            <p className="font-display text-2xl font-extrabold text-madder-600">₹{listing.suggested_price}</p>
          </div>
          <p className="flex items-center gap-1 text-right text-[11px] text-ink/60 leading-tight">
            <ShieldCheck size={14} className="text-indigo-500 shrink-0" />
            Anchored to verified
            <br />
            baseline: ₹{baseline.baseline_cost} ({baseline.item})
          </p>
        </div>

        {warning && (
          <p className="mt-3 rounded-lg bg-madder-50 px-3 py-2 text-[11px] text-madder-600 border border-madder-200">{warning}</p>
        )}

        {/* Action Buttons */}
        <div className="mt-4 space-y-2">
          {/* Button 1: Generate another listing */}
          <button
            type="button"
            onClick={onReset}
            className="flex w-full items-center justify-center gap-1.5 rounded-xl border-2 border-indigo-500/30 bg-white py-2.5 text-sm font-semibold text-indigo-600 transition active:scale-[0.98] hover:bg-indigo-50/50"
          >
            <RotateCcw size={15} />
            Generate another listing
          </button>

          {/* Button 2: Push to ONDC Network */}
          <button
            type="button"
            onClick={handleOndcPush}
            disabled={isSubmittingOndc}
            className={`flex w-full items-center justify-center gap-2 rounded-xl py-3 text-sm font-bold text-white shadow-md transition active:scale-[0.98] disabled:opacity-60 ${
              ondcSubmitted
                ? 'bg-emerald-600 hover:bg-emerald-700'
                : 'bg-gradient-to-r from-emerald-600 via-teal-600 to-indigo-600 hover:opacity-95'
            }`}
          >
            {ondcSubmitted ? (
              <>
                <CheckCircle2 size={16} />
                ONDC Live ✅
              </>
            ) : (
              <>
                <Share2 size={16} />
                {isSubmittingOndc ? 'Pushing to ONDC…' : 'Push to ONDC Network 🚀'}
              </>
            )}
          </button>
        </div>
      </div>
    </section>
  );
}
